"""add freebies table

Revision ID: ac964de1c36d
Revises: cf2b7a97af0d
Create Date: 2026-01-02 11:25:42.038135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac964de1c36d'
down_revision = 'cf2b7a97af0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
